# Generated by Django 3.2.8 on 2022-05-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelValues',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('landmark', models.CharField(max_length=255, verbose_name='Landmark')),
                ('turkish_male', models.FloatField(null=True, verbose_name='Turkish Male')),
                ('turkish_female', models.FloatField(null=True, verbose_name='Turkish Female')),
                ('caucasian_male', models.FloatField(null=True, verbose_name='Caucasian Male')),
                ('caucasian_female', models.FloatField(null=True, verbose_name='Caucasin Female')),
                ('korean_male', models.FloatField(null=True, verbose_name='Korean Male')),
                ('korean_female', models.FloatField(null=True, verbose_name='Korean Female')),
                ('brazil_male', models.FloatField(null=True, verbose_name='Brazil Male')),
                ('brazil_female', models.FloatField(null=True, verbose_name='Brazil Female')),
                ('indian_male', models.FloatField(null=True, verbose_name='Indian Male')),
                ('indian_female', models.FloatField(null=True, verbose_name='Indian Female')),
            ],
        ),
    ]
