# Generated by Django 3.2.8 on 2022-05-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvalues',
            name='german_female',
            field=models.FloatField(null=True, verbose_name='Indian Female'),
        ),
        migrations.AddField(
            model_name='modelvalues',
            name='german_male',
            field=models.FloatField(null=True, verbose_name='Indian Male'),
        ),
        migrations.AddField(
            model_name='modelvalues',
            name='srilankan_female',
            field=models.FloatField(null=True, verbose_name='Indian Female'),
        ),
        migrations.AddField(
            model_name='modelvalues',
            name='srilankan_male',
            field=models.FloatField(null=True, verbose_name='Indian Male'),
        ),
        migrations.AddField(
            model_name='modelvalues',
            name='taiwanese_female',
            field=models.FloatField(null=True, verbose_name='Indian Female'),
        ),
        migrations.AddField(
            model_name='modelvalues',
            name='taiwanese_male',
            field=models.FloatField(null=True, verbose_name='Indian Male'),
        ),
    ]
