# Generated by Django 3.2.8 on 2022-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablesapp', '0002_auto_20220529_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvalues',
            name='brazil_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Brazil Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='brazil_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Brazil Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='caucasian_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Caucasin Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='caucasian_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Caucasian Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='german_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='german_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='indian_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='indian_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='korean_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Korean Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='korean_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Korean Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='srilankan_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='srilankan_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='taiwanese_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='taiwanese_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Indian Male'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='turkish_female',
            field=models.CharField(max_length=255, null=True, verbose_name='Turkish Female'),
        ),
        migrations.AlterField(
            model_name='modelvalues',
            name='turkish_male',
            field=models.CharField(max_length=255, null=True, verbose_name='Turkish Male'),
        ),
    ]
