# Generated by Django 3.2.8 on 2022-05-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablesapp', '0004_auto_20220529_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelvalues',
            old_name='brazilain_male',
            new_name='brazilian_male',
        ),
    ]
